Adding info handler, that contains two fields, num objects and memory…
valkey-io/valkey-bloom pull request #19
Opened 2024-10-31 18:26 UTC by zackcam

Added an info handler which required updating Cargo.toml to include valkey-module-macros and linkme. The info handler contains two fields bloom_total_memory_bytes and bloom_num_objects. I then updated the creation and copy methods of bloom objects to increment these values where necessary. In order to deincrement added impl Drop for bloom in order to decrease the info fields as necessary.

Testing:
Created a new test file specifically for info. This test file contains for different tests:
test_basic_command_metrics: This tests all create commands and non create commands to check that create commands increase the info metrics while non create dont have an influence.
test_scaled_bloomfilter_metrics: Tests scaling a bloom filter increases the metrics as desired
test_copy_metrics: Tests copying a bloom filter will double the metrics as desired
test_save_and_restore_metrics: Tests saving and restoring a scaled and non scaled bloom filter will increase metrics as desired

2024-11-01 18:13 UTC, KarthikSubbarao requested changes

2024-11-01 18:13 UTC, KarthikSubbarao commented on src/configs.rs
> +    pub static ref BLOOM_OBJECT_TOTAL_MEMORY_BYTES: AtomicUsize = AtomicUsize::new(0);
This works. But for clarity, can we create a `src/metrics.rs` file? We can add both the lazy static and the info handler macro there

2024-11-01 18:13 UTC, KarthikSubbarao commented on src/bloom/utils.rs
> +        configs::BLOOM_NUM_OBJECTS.fetch_add(1, Ordering::Relaxed);
BLOOM_NUM_OBJECTS is the number of bloom objects. 

We can add a different metric, `BLOOM_NUM_FILTERS`, to track the number of filters created as a result of existing bloom objects

2024-11-01 18:13 UTC, KarthikSubbarao commented on src/bloom/utils.rs
> +        configs::BLOOM_OBJECT_TOTAL_MEMORY_BYTES.fetch_add(
We should increment `BLOOM_NUM_OBJECTS ` here, right?

2024-11-01 18:13 UTC, KarthikSubbarao commented on src/bloom/utils.rs
> +        configs::BLOOM_NUM_OBJECTS.fetch_add(1, Ordering::Relaxed);
We should not increment `BLOOM_NUM_OBJECTS` here. But, instead increment `BLOOM_NUM_FILTERS`.

You can first update all the right places for these two metrics. I will review the next commit where these are fixed

2024-11-01 20:55 UTC, YueTang-Vanessa commented on src/bloom/utils.rs
> +        configs::BLOOM_OBJECT_TOTAL_MEMORY_BYTES.fetch_add(
Why increase this metric here? What if there has error? Maybe consider to move this few lines below?

2024-11-01 21:42 UTC, YueTang-Vanessa commented on src/bloom/data_type.rs
> +            mem::size_of::<BloomFilterType>(),
Will there has duplicate memory add here as few lines above BloomFilter::from_existing will also increase same metric `BLOOM_OBJECT_TOTAL_MEMORY_BYTES`?

2024-11-01 21:53 UTC, zackcam commented on src/bloom/data_type.rs
> +            mem::size_of::<BloomFilterType>(),
I don't think so this never has from_exisitng or new called for BloomFilterType as far as I could see. This should also be caught in my rdb test if it would double up. I think its confusing because there is a from_existing in both BloomFilter and BloomFilterType. Does this make more sense now?

2024-11-01 23:10 UTC, zackcam commented
Accidently closed the pr, reopening with the following changes:

1. Moved the info handler to a separate file as well as the info metrics.
2. Created a new metric for number of filters (Changed the other metric to actually be number of bloom objects)
3. Updated tests to include this new metric
4. Moved an increment of metrics to be after a possible thrown error

2024-11-01 23:35 UTC, YueTang-Vanessa commented on tests/test_bloom_metrics.py
> +        assert num_objects == expected_num_objects
Missing `assert num_filters == expected_num_filters`

2024-11-01 23:37 UTC, YueTang-Vanessa commented on tests/test_bloom_metrics.py
> +
Nit pick: may just keep one newline

2024-11-01 23:40 UTC, YueTang-Vanessa commented on tests/test_bloom_metrics.py
> +    def test_basic_command_metrics(self):
Can you also add one test case of key expiration? Use `EXPIRE` for a bloom filter key, and see if all metrics works as expected.

2024-11-01 23:54 UTC, zackcam commented on tests/test_bloom_metrics.py
> +    def test_basic_command_metrics(self):
Added this case in test_basic_command_metrics

2024-11-02 00:01 UTC, YueTang-Vanessa approved these changes
LGTM

2024-11-05 00:57 UTC, KarthikSubbarao commented on src/metrics.rs
> +            "bloom_num_filters",
`bloom_num_filters_across_objects`

2024-11-05 00:57 UTC, KarthikSubbarao commented on src/metrics.rs
> +    pub static ref BLOOM_NUM_OBJECTS: AtomicUsize = AtomicUsize::new(0);
Can we have this as a u64?

2024-11-05 00:57 UTC, KarthikSubbarao commented on src/metrics.rs
> +    pub static ref BLOOM_NUM_FILTERS: AtomicUsize = AtomicUsize::new(0);
Can we have this as a u64?

2024-11-05 01:02 UTC, KarthikSubbarao commented on tests/test_bloom_metrics.py
> +    def verify_bloom_metrics(self, info_response, expected_memory, expected_num_objects, expected_num_filters):
Can we move this into the main valkey bloom test class?

2024-11-05 05:10 UTC, zackcam commented on tests/test_bloom_metrics.py
> +    def verify_bloom_metrics(self, info_response, expected_memory, expected_num_objects, expected_num_filters):
Moved and comment is updated

2024-11-05 19:35 UTC, KarthikSubbarao commented on src/lib.rs
> +    create_info_handler(ctx)
Nit: A better name could be: `bloom_info_handler`

This fits well as if we add other data types, we can add more x_info_handlers to this function

2024-11-05 19:35 UTC, KarthikSubbarao commented on src/lib.rs
> +fn add_info(ctx: &InfoContext, _for_crash_report: bool) -> ValkeyResult<()> {
Nit: A better name could be: `info_handler`

2024-11-05 20:01 UTC, merged