Integration tests for commands, delete operations, expiry
valkey-io/valkey-bloom pull request #7
Opened 2024-10-03 01:31 UTC by YueTang-Vanessa

This commit includes following changes:

* Add test for bloom command arity, behavior and basic error
* Set up a base case for valkey bloom filter module
* Set info of expansion to Null for NONSCALING mode
* Add test for basic valkey command

2024-10-03 18:46 UTC, zackcam commented on src/bloom/utils.rs
> +pub const BAD_EXPANSION: &str = "Bad expansion";
Should we also capitalize the other error messages first words?

2024-10-03 18:51 UTC, zackcam commented on tests/test_basic.py
>  from valkeytests.conftest import resource_port_tracker
Could you test if we move this import to valkey_bloom_test_case.py if tests still work? Cause if so we wont need to add this import to every test in the future

2024-10-03 19:07 UTC, zackcam commented on tests/test_basic.py
> +        assert client.execute_command('BF.MEXISTS LUA2 ITEMS2 ITEMS3 ITEMS4') == [0, 1, 1]
Maybe just for readability but the checking against ITEMS2 when ITEM2 is in was kinda easy to gloss over the S, so confused me for a bit on why it didn't exist. Would ITEM1 work instead as thats probably more readable?

2024-10-04 21:37 UTC, YueTang-Vanessa commented on src/bloom/utils.rs
> +pub const BAD_EXPANSION: &str = "Bad expansion";
Nah, this is by design.

2024-10-04 21:43 UTC, YueTang-Vanessa commented on tests/test_basic.py
>  from valkeytests.conftest import resource_port_tracker
> Could you test if we move this import to valkey_bloom_test_case.py if tests still work? Cause if so we wont need to add this import to every test in the future

I tried to move this line `from valkeytests.conftest import resource_port_tracker` to `valkey_bloom_test_case.py` before, running tests locally won't have any issues, but when I push that in the github, I can see the workflow fail. See [this workflow](https://github.com/YueTang-Vanessa/valkey-bloom/actions/runs/10951218250) I think we can probably work on that later

2024-10-04 21:45 UTC, YueTang-Vanessa commented on tests/test_basic.py
> +        assert client.execute_command('BF.MEXISTS LUA2 ITEMS2 ITEMS3 ITEMS4') == [0, 1, 1]
> Maybe just for readability but the checking against ITEMS2 when ITEM2 is in was kinda easy to gloss over the S, so confused me for a bit on why it didn't exist. Would ITEM1 work instead as thats probably more readable?

Sounds good. Will do it

2024-10-07 21:50 UTC, KarthikSubbarao requested changes

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/valkey_bloom_test_case.py
> +            print("Something went wrong in command behavior verification")
Can we add a new line here?

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +        assert self.client.execute_command('FLUSHALL')
Do we need to execute flushall at the beginning of the test? Doesn't a new server startup at this point?

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.INFO TEST Capacity', 100),
Can we test other variations? `BF.INFO TEST filters` and `BF.INFO TEST`

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.INSERT TEST CAPACITY 200 error 0.99 ITEMS ITEMS ITEMS1 ITEMS2', [0, 1, 1]),
Nit: Creating a filter with 0.99 error rate will likely make this test flaky in terms of false positives (it can indicate that these items exist even though we did not add them). If you are adding a test where you are asserting that an item add succeeds (returning 1), we should probably use a smaller error rate

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +        assert self.client.execute_command('BF.ADD bf_non 1') == 1
Let's move this block of code to the start of the test so that we know it is a "setup" for this particular test

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_basic.py
> +        assert client.execute_command('BF.MEXISTS LUA2 ITEMS2 ITEMS3 ITEMS4') == [0, 1, 1]
Would be good if this is in a separate test for transactions and lua

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_basic.py
> +        assert client.execute_command('TTL TEST_PERSIST') == -1
We can move this to a expiration test

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_basic.py
> +        assert client.execute_command('TOUCH key1 key2') == 2
Let's have one test for all delete operations called test_bloom_deletes. DEL, UNLINK, FLUSHALL

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('bf.reserv', 'unknown command \'bf.reserv\', with args beginning with: '),
We can remove this case. Invalid command names are not really a bloom specific behavior (the core engine will reject this)

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_basic.py
> +        assert client.execute_command('BF.EXISTS filter1 item1') == 0
1. Can we also test the `EXISTS` command here? We can use EXISTS before deleting and it should succeed. After deleting, the command should return 0 / indicate that it does not exist.

2. Similarly, we can check num_keys before and after the delete operation. 

If we can do this for all operations including: DEL, UNLINK, FLUSHALL, and for expiration that will help validate correct creation and deletion

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_basic.py
> +        time.sleep(1)
Instead of using sleep, if we use wait_for, it will help reduce flakiness

2024-10-07 21:50 UTC, KarthikSubbarao commented on tests/test_basic.py
> +        assert client.execute_command('BF.MEXISTS LUA2 ITEMS2 ITEMS3 ITEMS4') == [0, 1, 1]
Nit: ITEMS2 confused me with ITEM2 :D 

Can we use either ITEM or ITEMS for the entire test? If we are using ITEM, we can just use ITEM1, ITEM2 ...  instead of adding ITEMS2

2024-10-08 00:49 UTC, KarthikSubbarao commented on tests/valkey_bloom_test_case.py
> +    def verify_command_behavior_as_expected(self, client, cmd, expected_result):
Nit: A shorter name would be `verify_command_success_reply` or `verify_command_success_response`

2024-10-08 00:49 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.RESERVE KEY SSS SSS', 'bad error rate'),
[For BF.RESERVE and BF.INSERT] Could we add limit tests for the capacity, expansion, and false positive rate? For example, expansion is only allowed within a certain limit (1 to 10). Capacity (1 to u32::MAX). 

false positive rate has a precision of f32. Example:  Parsing `0.99999999` as f32 becomes 1

2024-10-08 01:18 UTC, YueTang-Vanessa commented on tests/test_basic.py
> +        time.sleep(1)
As we discussed offline, will keep the sleep here for the OBJECT IDLETIME test, will use wait_for from util for the EXPIREAT command

2024-10-08 01:19 UTC, YueTang-Vanessa commented on src/bloom/utils.rs
> +pub const BAD_EXPANSION: &str = "Bad expansion";
As discussed offline with Karthik, will add bad the ERR prefix to keep our message consistent.

2024-10-09 03:02 UTC, KarthikSubbarao commented on tests/test_redis_bloom_compatibility.py
> +class TestRedisBloomCompatibility(ValkeyBloomTestCaseBase):
We can update to: `TestValkeyBloomCompatibility`

2024-10-09 03:02 UTC, KarthikSubbarao commented on tests/test_redis_bloom_compatibility.py
> +    #         assert decoded_r.bf().exists("pipeline", i)
Why is this commented? Was this from the original valkey-py test file for bloom?

2024-10-09 03:02 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.ADDX TEST KEY', 'unknown command \'BF.ADDX\', with args beginning with: \'TEST\' \'KEY\' '),
We can remove this test case since the `BF.ADDX` command does not exist

2024-10-09 03:02 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.EXIST KEY', 'unknown command \'BF.EXIST\', with args beginning with: \'KEY\' '),
We can remove this test case since the `BF.EXIST` command does not exist

2024-10-09 03:02 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.RESERVE TEST_CAP 0.50 0', '(capacity should be larger than 0)'),
Can we test the same scenario for `BF.INSERT`?

2024-10-09 03:02 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.RESERVE bf 0.01 1000', 'item exists'),
Can we test a NOCREATE scenario for BF.INSERT?

2024-10-09 03:02 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.INSERT KEY error 2 ITEMS test1', '(0 < error rate range < 1)'),
Can we test this same scenario (error rate outside range) for BF.RESERVE?

2024-10-09 03:02 UTC, KarthikSubbarao commented on tests/test_redis_bloom_compatibility.py
> +import pytest
Let's rename the file to `test_valkeypy_bloom_compatibility.py` or `test_valkeypy_bloom_compat.py`

2024-10-09 19:26 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.INSERT TEST_CAPACITY CAPACITY 2000 ITEMS ITEM', [1]),
Can we also add this test case?
```
BF.INSERT <key> ITEMS 1 2 3 EXPANSION 2
```
Here, `1 2 3 EXPANSION 2` are all treated as items. So we should have an array reply with 5 integers

2024-10-09 19:26 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('BF.INSERT KEY HELLO WORLD', 'wrong number of arguments for \'BF.INSERT\' command'),
This should return a unknown arg error and looks like it will need a small code change in the BF.INSERT handler

2024-10-09 19:26 UTC, KarthikSubbarao commented on tests/test_bloom_command.py
> +            ('bf.insert key CAPACITY 10000 ERROR 0.01 EXPANSION 0.99 NOCREATE NONSCALING ITEMS test1 test2 test3', 'bad expansion'),
Can we add a test case for the command variation below?
```
BF.INSERT <key> EXPANSION 2
```

This should return a WRONG ARITY error and looks like it will need a small code change in the BF.INSERT handler

2024-10-09 21:00 UTC, YueTang-Vanessa commented on tests/test_redis_bloom_compatibility.py
> +    #         assert decoded_r.bf().exists("pipeline", i)
> Why is this commented? Was this from the original valkey-py test file for bloom?

Yes, this is from the [valkey-py/test-bloom.py](https://github.com/valkey-io/valkey-py/blob/main/tests/test_bloom.py#L492-L505)

2024-10-09 22:52 UTC, merged